[package]
name = "voxel_map"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
delaunator = "1.0.1"
rand = "0.8.4"
#rust-3d = "0.34.0"
kiss3d = "0.35.0"
nalgebra = "0.31.3"