[package]
name = "ps_visualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ps_data_layer = { path = "../ps_data_layer" }
kiss3d = "0.32"
nalgebra = "0.32.2"
notify = "4.0.15"